### ISSUE TITLE
[Bug]: GitHub PR CI incorrect

### ISSUE THREAD

**Issue by JamesHawkinss** [movie-web/movie-web#190]
### What happened?

On pull requests, linters check against destination branch rather than source branch. Bad!

### Other relevant information

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by frost768** [comment]
so instead of using `pull_request_target`, using `pull_request` in workflow will solve the problem since the latter one checks out pull request's base rather than target's base
[Here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) it explicitly says
 _Avoid using this event if you need to build or run code from the pull request_

**Comment by mrjvs** [comment]
@frost768 problem of using the pull_request event is that we need to have the checks:write permission for linting annotations.
so just switching to that event wouldn't have fixed the problem.

I fixed it by making a seperate workflow with the workflow_run event. so the annotation is a completely seperate workflow but uses the artifacts of a normal pull_request workflow.

anyway, its now resolved

**Comment by frost768** [comment]
@mrjvs thanks for the thorough explanation
