### ISSUE TITLE
[Feature]: Subtitles should be separate from the settings button

### ISSUE THREAD

**Issue by yilmazcabuk** [movie-web/movie-web#286]
### What feature do you want to add?

Currently, the subtitles option is located within the settings menu, making it difficult for users to quickly enable or disable subtitles. This can be particularly problematic for those who prefer to watch videos with subtitles.

### Why do you want to have this feature?

It would be great if the subtitles option could be separated from the settings menu and placed in a more prominent location, such as on the video player itself. This would allow users to quickly and easily enable or disable subtitles without having to navigate through multiple menus.

**Comment by mrjvs** [comment]
it was initially moved to the settings menu due to the clutter of having a lot of buttons.
it was overwhelming to users to see that many options at once and a settings menu makes it easier to add new features.

If enough people wants this feature, we can consider moving it back. but for now we're keep it as is.
I'm gonna keep this issue open to see reactions of other users.

**Comment by VirginitySnatcher** [comment]
I like the idea of having captions as a separate button. I was thinking if you can add an option to toggle captions to either be hidden in the settings menu like it is now, or you could enable them to be separate?   🤔

**Comment by mrjvs** [comment]
tracked by #338. closing
