### ISSUE TITLE
[Feature]: A discover section

### ISSUE THREAD

**Issue by tester248** [movie-web/movie-web#311]
### What feature do you want to add?

Something like a discover section which would display a list of top (Popular and Featured) movies & series in different genres.
It should be doable with the data you get from imdb I think maybe.
This would look good if integrated in the home page of the website, but having a separate tab to discover/explore content would be better it'll maintain the clean look of the website.
Something similar to Stremio (https://app.stremio.io) would be neat.
I'll attach some screenshots of stremio for reference

<img width="956" alt="image" src="https://github.com/movie-web/movie-web/assets/74985969/13a785ba-96b1-4e5d-9674-66cca6695136">
<img width="959" alt="image" src="https://github.com/movie-web/movie-web/assets/74985969/37bddd56-8712-4327-ae16-afd10ea92b07">

### Why do you want to have this feature?

So we can explore content before watching
For aesthetics

**Comment by mrjvs** [comment]
I'm gonna close this, it's not in scope of the project.

The main reason why we don't is because we'll be too much like every other streaming site.
There are hundreds if not thousands of streaming sites out there.

If we copy from how other sites do it, then we're just gonna be yet another streaming site, there would be no point to use movie-web as we'd just be the same as every site.

Instead of that, we decided to focus more on the audience that just want to watch something they heard from a friend but can't find it on the paid streaming services they are subscribed to.

We're not gonna have an algorithm or a trending section, it's all going to be the exact choice of the user of what to watch.
We don't want people to mindlessly consume whatever is on the front page.

If you want the features of a standard streaming site, use those other streaming sites. Not this one.

**Comment by abel-mak** [comment]
hello @mrjvs
I got issue i created earlier closed and i completely understand the vision of the project and admire the great work you've done with the website. but i wanna add something, about making algorithm you mentioned i think the api you are using have that already, and for keeping the website simple and about users "mindlessly consume whatever is on the front page" you can make a button that goes the page of popular. that being said i respect your choice and the website is great already.
