### ISSUE TITLE
[Feature]: Dedicated Android TV Support

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#319]
### What feature do you want to add?

Ideally for large screens movie-web should provide a tv/remote friendly UI in a similar fashion to YouTube and other services, I believe all it needs to be remote friendly is keyboard navigation 

Furthermore this should be bundled as android tv app (effectively just chrome webview bundled as apk with a harcoded destination) to be installable on all Android TVs such as Google TV, Amazon Fire TV etc...

### Why do you want to have this feature?

Whilst casting is great and functional, it still feels like a big screen UI would be something one should have

### Anything other details to share?

not really no, but leaving a question empty would be rude

**Comment by castdrian** [comment]
> Can you give some examples?

https://www.youtube.com/tv however since a couple years ago it checks the user agent so you need to spoof it 

https://chrome.google.com/webstore/detail/youtube-tv-on-pc/jldjbkccldgbegjpggphaeikombjmnkh?hl=en-GB

**Comment by castdrian** [comment]
In the meantime I've bundled a webview that loads movie-web and contains dedicated cursor controls for remotes

https://github.com/castdrian/movie-web-tv

**Comment by mrjvs** [comment]
Out of scope for movie-web, although maybe in the future we will. but not in this web version

**Comment by DarkCrypt** [comment]
> Out of scope for movie-web, although maybe in the future we will. but not in this web version

No offense but that really sucks. An Android TV version of movie-web would be kickass! The proper device to watch movies/tv shows is a television. Especially since Smart TV's and Android TV boxes have completely taken over what we all knew a television was.

I tried castdrian's above webview apk on my Android TV box and it works well enough to be useable as an alternative to an actual build. This apk is much better than using a TV browser or casting because neither of these 2 ways are very convenient. I think a webview apk for mobile would be cool too.

Just my opinion.

**Comment by castdrian** [comment]
for mobile you can just install the PWA

**Comment by DarkCrypt** [comment]
> for mobile you can just install the PWA

True, it's basically the same thing as "Add to Home screen" but without the browser functions. Sorry but I don't see the point of a PWA just to eliminate the browser functions. To me this is pretty much the same thing as putting a website into a webview. Installing the PWA also includes the browser logo on top of the website logo at the bottom corner which looks silly to me.

A webview apk only has the website logo, is more native, and is an easy build compared to full blown apps. If you want you can also add more functionality.

I don't watch movies on mobile(even though I have over 20+ free streaming apps installed) because I prefer watching on my tv. But I will definetly keep movie-web in my bookmarks.

**Comment by mrjvs** [comment]
theres a few problems with a webview apk:
 - webviews on TV browsers use the TV's builtin browser. We've had tons of reports of movie-web not working on TV browsers. So actual user count that could use it would be very low.
 - We've put in pretty much 0 effort in navigation for TV. It's quite a chore to make stuff compatible with remote. especially since we have such a complex UI (the video player). I'd rather have a dedicated built app rather than trying to bloat the website codebase to target every possible device.
 
 
This is why it's out of scope for the website. However that doesn't mean we'll never consider building a TV native app. In fact, the pieces are being set into place to allow for code sharing between different platform. We're looking at it, just not *now*.

**Comment by mrjvs** [comment]
also I'd like to add there is chromecasting support, so android TV's can be casted to from your android phone.

**Comment by DarkCrypt** [comment]
Webviews work on Android System Webview which is a builtin system app on all Android devices. I have seen many users complain about this system app.

I can understand remote functions would be very difficult to implement.

I also understand Chromecast is supported but I'm not a fan of casting. It's easy to have issues.

Thank you for the replies. I'll stop bothering you about this feature, not trying to be a headache.

**Comment by DarkCrypt** [comment]
Just posting for awareness. D-pad navigation support for web apps.

GitHub repo: [D-pad Navigation](https://github.com/gauntface/dpad-navigation)
