### ISSUE TITLE
[Feature]: Having a 'Surprise Me' feature 

### ISSUE THREAD

**Issue by singhrohan62** [movie-web/movie-web#372]
### What feature do you want to add?

A 'Surprise Me' option, when picked by the user, will try to get a list of movies randomly selected from the movies list and will render on the screen.

### Why do you want to have this feature?

I personally felt while going through the application, that the main page of the application should have an option like 'Surprise Me' because I think that the application forces the user to enter the movie name, I felt that if the user wants to randomly watch some movie and is not able to figure out what to watch, this feature might be helpful.

### Anything other details to share?

Even Audio streaming platforms have this feature, which can be useful when user feels like streaming a random movie.

**Comment by castdrian** [comment]
Whilst random playback is nice, it usually relies on the platforms algorithm to match something that fits your taste, I don't see a feasible way of doing that, can't really get just a random title, best tmdb offers is a list of top rated or most popular titles

**Comment by singhrohan62** [comment]
> Whilst random playback is nice, it usually relies on the platforms algorithm to match something that fits your taste, I don't see a feasible way of doing that, can't really get just a random title, best tmdb offers is a list of top rated or most popular titles

Or, we could have the list of top 10 most searched/viewed movies in the application and show them under this feature. What do you think about this ?

**Comment by lem6ns** [comment]
> > Whilst random playback is nice, it usually relies on the platforms algorithm to match something that fits your taste, I don't see a feasible way of doing that, can't really get just a random title, best tmdb offers is a list of top rated or most popular titles
> 
> Or, we could have the list of top 10 most searched/viewed movies in the application and show them under this feature. What do you think about this ?

we don't log whats being watched on a db, so this cant be implemented

**Comment by mrjvs** [comment]
few potentional logistical problems with this feature:
 1. whats the source of movies to choose from? Since we use a database (tmdb) that doesnt match our actual catalog, 90% of random item will be stuff we dont actually have. (since we scrape on demand, we dont know what sources have what movies). Same with the newly released or popular lists, those are filled with movies we dont have.
 2. usually these features are based on users searched and an algorithm to determine your taste in movies, since we dont store *anything* about what is searched or watched. we cant predict what movies will be liked (or which we have, as for point 1)
 
 ps: me commenting on this doesn't explicitely mean it will be worked on, im just bringing up problems that will need resolving before we consider adding it.

**Comment by castdrian** [comment]
I would guess that the likelihood of the most popular titles from tmdb/the top voted titles being available is at about 99%, excluding titles that are yet to be released on digital platforms, so the issue I would be mostly, do we really want to waste worker bandwidth on random empty results?

**Comment by zisra** [comment]
The tmdb api allows you to see if something is released digitally: https://developer.themoviedb.org/reference/movie-release-dates . Probably not specific to this issue but still useful

**Comment by binaryoverload** [comment]
No longer planned, out of scope
