### ISSUE TITLE
[Feature] Support for German language

### ISSUE THREAD

**Issue by sami155** [movie-web/movie-web#392]
I wish for support for German dubs of shows.

Well knows websites are: bs.to, s.to/serienstream.to

They use following hosters: Voe.sx, Streamtape, Vidoza and Doodstream,

**Comment by zisra** [comment]
<img width="905" alt="Screenshot 2023-07-31 at 11 55 11 AM" src="https://github.com/movie-web/movie-web/assets/100528712/834fbf9e-4c22-45a5-93ca-31bd20043ec7">
Were they not taken down?

**Comment by castdrian** [comment]
All of those use embeds that can't be accessed

**Comment by Triky313** [comment]
Hay, is there any way to speed this up?
I am a .net developer but would like to help.
Can't you make a little guide so that you know what files need to be added for a German provider as well as other languages?

Of course you would have to provide a selection in the main menu for which providers and languages you want to search, but I would then rebuild and add the rest myself.

**Comment by JipFr** [comment]
Dubs are currently not in scope. Many sources also don't provide the language something is in, so even if it was in scope, it would still be an unstable feature at best.

**Comment by zisra** [comment]
@JipFr this issue is a request for new sources, not for the current sources to provide German

**Comment by JipFr** [comment]
The issue is that we'd need to introduce a language picker when we can't possibly know what language a video is in. Take anime: while we don't officially support it, some series are on some sources. Some of those videos are dubbed, others subbed. The sources don't tell us which it is, so what language do we tell the user the video is in? "Unknown"? That'd make it impossible to filter, which would be very poor UX. You don't want English speakers to randomly start watching the German dub of something that was originally made in English.

Also, it's out of scope. :P

**Comment by Triky313** [comment]
I understand that.
Nevertheless, this can be made portal-dependent or not?

So currently all active providers are for English-language films. However, there are also providers that can be exclusively for German films or series, or where this can be selected beforehand.

"https://bs.to/", for example, always shows in the URL whether English or German. This is the largest series portal in Germany, Austria and Switzerland.

I think it is already possible to use certain providers for specific languages.
