### ISSUE TITLE
[Feature]: Weblate translations

### ISSUE THREAD

**Issue by jonbarrow** [movie-web/movie-web#446]
### What feature do you want to add?

The use of [Weblate](https://weblate.org/) to manage translations

### Why do you want to have this feature?

Currently translations are managed simply by PRs, which over time can become cumbersome to manage and clutter up GitHub issues/PRs. Weblate creates a platform to track the status of translations, and create new ones, very easily. It also integrates with GitHub to merge in translations as they progress, so that they can be PRed in bulk

### Anything other details to share?

Weblate has paid plans but is free if self hosted or if used for a FOSS project. More info about hosting can be found [here](https://weblate.org/en/hosting/). We have been using Weblate over at Pretendo, using the FOSS package, for quite some time to manage our translations for our website (30 languages) and Miiverse replacement (28 languages), so I can vouch for it's usability. Here is an example of what the dashboard looks like with many in-progress translations https://hosted.weblate.org/projects/pretendonetwork/

**Comment by mrjvs** [comment]
I was already planning on using weblate for this after we release the next version.
I've used it before and think its a good fit.

I don't want to use the hosted version, as that needs manual approval from weblate and im not sure if theyd enjoy a piracy platform on their website. So we'll selfhost it on the vps we already have.

But like I said, gonna set it up after we have v4 ready, as otherwise people would contribute translations that would no longer exist after the rewrite.

**Comment by mrjvs** [comment]
We now use weblate for translations
