### ISSUE TITLE
[Bug]: Backend captcha's are not working

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#544]
### What happened?

- captcha's not working correctly

**Comment by spewmaker** [comment]
Are there any steps to reproduce this bug?

**Comment by Caio-Nogueira** [comment]
Could you provide more details about this? At the moment, captcha assertion is not being performed, so we can't see what is actually wrong with it

**Comment by mrjvs** [comment]
When we enabled the captcha support on movie-web production. All captchas failed, making nobody be able to sign up. This could be a client issue or backend, not sure.

Thats the context of the bug, hope that helps @Caio-Nogueira

**Comment by Caio-Nogueira** [comment]
Alright, I did a little bit of research of my own, since the code seemed just fine to me, and I wasn't able to verify the token even by calling the API through Postman. 

I actually found [this Stackoverflow thread](https://stackoverflow.com/questions/52416002/recaptcha-error-codes-missing-input-response-missing-input-secret-when-v) that you should not use JSON to send the response code. Instead, this endpoint only accepts the `application/x-www-form-urlencoded`.

I tried changing the request locally and it worked, so all you need is a simple backend change. I could PR this if you assign it to me

**Comment by mrjvs** [comment]
Assigned!
