### ISSUE TITLE
[Feature]: Improve mobile UX

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#62]
see title

**Comment by JamesHawkinss** [comment]
![image](https://user-images.githubusercontent.com/40138757/166153653-bdcb8a35-5478-450c-87bf-5e0aeb791de4.png)

**Comment by JamesHawkinss** [comment]
![image](https://user-images.githubusercontent.com/40138757/166153693-11fc41e9-becf-4d55-b09d-afff63553fc9.png)

**Comment by mrjvs** [comment]
WIP design:
<img src="https://i.imgur.com/IFOcekT.png">

**Comment by maxwellward** [comment]
Hey guys, if this isn't already being worked on I'd potentially be interested in picking this up if it's available. 

Taking a look at @mrjvs 's designs, if I may provide some feedback, I think the current (v3) design works pretty well on mobile so these changes (with the source and no cover art) might be null and void now.

From what I can tell, these are the following issues with mobile in v3:

- Too much vertical space under the search bar before the bookmarks. This works well on desktop, but could probably be half the size on mobile.
- The "Movie/Series" dropdown does not stay within its container when scrolling the page (this occurs on desktop too).
- The "What do you want to watch" title goes over the logo and social buttons when scrolling down.
- The search dropdown leaves its container when the search field is active + scrolling.
- When a movie/series is loading, the "movie-web" branding can probably have it's text removed, and only show the logo, in order to have more space for the name of the content when in portrait mode (as people will likely still be in portrait mode at this stage).
- The dropdowns in the media player have their tops cut off in landscape mode, meaning some options are inaccessible.

Please let me know what you think, and if I'm able to take on this issue 😄 Great work on V3 guys.

**Comment by mrjvs** [comment]
closed, not descriptive enough
