### ISSUE TITLE
[Feature]: Improve how to change seasons

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#754]
### What feature do you want to add?

Instead of having a left facing arrow, make the season selector active with a "seasons" button top right of the episode selector popout.

### Why do you want to have this feature?

In v3, we made a similar change and we got way less reports and questions about how to switch seasons.
In v4 we accidentally reverted this change.

**Comment by CelestialLemon** [comment]
If it's possible I'd like to work on this. Might take me longer but looks like a good learning opportunity.

**Comment by mrjvs** [comment]
@CelestialLemon ive assigned you. You can find the code for it in /src/components/player/atoms/episodes.tsx

**Comment by CelestialLemon** [comment]
@mrjvs. I really haven't been getting the time to work on this. Can you please re-assign this to someone else. I'm really sorry for the trouble and delay caused. Just don't want to leave this hanging especially since it's tagged for V5 and I except it is important to get done. Again please forgive for not conveying this earlier.

**Comment by mrjvs** [comment]
No worries mate, if there was priority on this issue, the main team would have done it. So don't feel bad.

I've unassigned, thanks for letting us know.

**Comment by mrjvs** [comment]
I no longer maintain this project.
@binaryoverload can you help them out?
